# Generated by Django 6.0.5 on 2026-05-11 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='questions',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
