# Generated by Django 6.0.5 on 2026-05-11 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_remove_quiz_questions_delete_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='video_url',
            field=models.URLField(),
        ),
    ]
