# Generated by Django 6.0.5 on 2026-05-11 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0004_question_alter_quiz_description_alter_quiz_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='questions',
            field=models.ManyToManyField(related_name='questions', to='quizzes.question'),
        ),
    ]
