# Generated by Django 6.0.5 on 2026-05-12 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0005_quiz_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='questions',
            field=models.ManyToManyField(related_name='quizzes', to='quizzes.question'),
        ),
    ]
